name: LineageOS 23 Build for Galaxy S7 Edge (herolte)

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git bc bison build-essential ccache curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-17-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo

    - name: Initialize LineageOS 23 source (Android 16)
      run: |
        mkdir -p ~/android/lineage
        cd ~/android/lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-23.0
        repo sync -c -j$(nproc) --force-sync

    - name: Clone Galaxy S7 Edge device sources
      run: |
        cd ~/android/lineage
        git clone https://github.com/LineageOS/android_device_samsung_herolte device/samsung/herolte
        git clone https://github.com/LineageOS/android_kernel_samsung_universal8890 kernel/samsung/universal8890
        git clone https://github.com/TheMuppets/proprietary_vendor_samsung vendor/samsung

    - name: Build ROM
      run: |
        cd ~/android/lineage
        source build/envsetup.sh
        lunch lineage_herolte-userdebug
        mka bacon -j$(nproc)

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: lineage-herolte-rom
        path: ~/android/lineage/out/target/product/herolte/*.zip
