name: Build LineageOS 23 for herolte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 720

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison build-essential ccache curl flex g++-multilib \
          gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
          lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev \
          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop \
          openjdk-17-jdk pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev

    - name: Setup repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Initialize repo
      run: |
        mkdir -p $HOME/android/lineage
        cd $HOME/android/lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-23.0 --depth=1
        repo sync -c -j$(nproc) --force-sync

    - name: Clone device and vendor trees
      run: |
        cd $HOME/android/lineage
        git clone https://github.com/LineageOS/android_device_samsung_herolte device/samsung/herolte || true
        git clone https://github.com/LineageOS/android_kernel_samsung_universal8890 kernel/samsung/universal8890 || true
        git clone https://github.com/TheMuppets/proprietary_vendor_samsung vendor/samsung || true

    - name: Setup ccache
      run: |
        mkdir -p $HOME/.ccache
        echo "max_size = 20.0G" > $HOME/.ccache/ccache.conf
        export CCACHE_DIR=$HOME/.ccache
        export USE_CCACHE=1

    - name: Build LineageOS
      run: |
        cd $HOME/android/lineage
        source build/envsetup.sh
        lunch lineage_herolte-userdebug
        make bacon -j$(nproc)

    - name: List build output
      run: |
        ls -lah $HOME/android/lineage/out/target/product/herolte

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: lineageos-herolte
        path: $HOME/android/lineage/out/target/product/herolte/*.zip
        retention-days: 7
